### PR TITLE
More realistic flight

### PR DESCRIPTION
**Pull request by KosmX**
If you wanted realistic flight, why was this feature not implemented?!

If you roll left, you'll slowly turn left, depending on how much did you roll in and your speed.  

> Note, the math is not physically accurate.

### CODE REVIEW

**Comment by enjarai** [comment]
I've gotten similar suggestions on other platforms as well, and I'm definitely interested in merging this. However, it's important that it feels good to fly with, so I'll test it a bit ingame first and maybe tweak some values.

**Comment by KosmX** [comment]
I started tweaking in https://github.com/KosmX/do-a-barrel-roll/tree/tweak branch

**Comment by enjarai** [comment]
The yaw changes are nice, but I feel like they'd work better with more continuous movement, which is exactly what the tweak branch removes by making the smoothing more snappy. However, this snappiness is also a good thing as it makes the player more maneuverable, although I do feel its a little too sensitive right now.

Both changes work fine on their own, but demerit eachother when put together. I think the solution would be momentum based camera movement where, if you move your mouse up for example, the camera will keep pitching up until the mouse is moved down again. A lot of space sim games I know use this approach, since it makes more gradual turns possible without having to keep moving your mouse.

What do you think?

**Comment by enjarai** [comment]
I should also mention that the yaw movement in the tweak branch is *way* too fast and snappy, that should definitely be more smoothed.

**Comment by KosmX** [comment]
The player is not a large airplane, making it too smooth makes it almost impossible to maneuver in small places/caves.  
Maybe it should be configurable.

The momentum based camera is a good idea, but for that, the mouse handling has to be reimplemented.

**Comment by enjarai** [comment]
I know I brought it up, but the momentum based camera would also probably need an onscreen widget to make it more intuitive. That makes it way more complex, so I'd say that goes on the backburner for a bit. Lets focus on getting the parameters for "autoyaw" and general responsiveness right first.

Maybe maneuverability should be based on the speed the player is flying at? And maybe the "autoyaw" should be less agressive at high speeds, it feels like you contantly have to be pitching up while flying.

**Comment by itsmiir** [comment]
i disagree; i think the turning should be even snappier. flying around in non-straight caves is almost impossible as it is compared to vanilla controls. probably won't be easy to do while also making the autoyaw (banking, as it would be called in aviation) feel realistic; might be a good thing to make configurable

**Comment by XanderCreates** [comment]
With this version of the mod with its modified flight physics i feel like i am fighting the controls..

**Comment by enjarai** [comment]
Seeing as the snappiness seems to be a very opinionated thing, I could keep it as it is now, but implement a config option to change it.

**Comment by KosmX** [comment]
New PR: https://github.com/enjarai/do-a-barrel-roll/pull/7

**Pull request closed without merging**
