### PR TITLE
MidnightControls Support

### PR DESCRIPTION
**Pull request by INotDen**
I think I kind of did it right, but I'm not sure. And about the translations too

### CODE REVIEW

**Comment by INotDen** [comment]
Something went wrong with changes

**Comment by enjarai** [comment]
I'd actually removed support for MidnightControls which I used to have in favor of Controlify support, as it's more modern and easier to work with. Is there any particular reason to use Midnight over Controlify?

**Comment by INotDen** [comment]
II'm still a 1.19.4 player, I'm waiting for most mods to be updated, and Controlify is not very good on 1.19.4. Plus, for my case, I have a clone of xbox gamepad, and all applications see it as not necessary (A instead of B, X instead of Y, ...) and surprisingly, MidnightControls sees it perfectly.
I still don't know for myself how much longer I will stay at 1.19.4.
I do not know English, so maybe there are lexical errors in my message.
I decided to do a pull, just in case you're interested.

**Comment by INotDen** [comment]
I think you can leave this as a legacy for 1.19.4 without doing a merge in 1.20, but idk

**Comment by enjarai** [comment]
Okay yea fair enough, thanks for contributing!

**Comment by INotDen** [comment]
Sorry

**Pull request merged**
